export default `
<div id="doc" class="markdown-body container-fluid comment-enabled" data-hard-breaks="true"><p class="timestamp"><strong><span>Last updated January 11, 2023</span></strong></p><p><span>CSMA Technology, LLC built the Blend app as a Free app. This SERVICE is provided by CSMA Technology, LLC at no cost and is intended for use as-is.</span></p><p><span>Blend does not collect, store, or share any personal data. However, it does collect usage information for the purpose of troubleshooting and improving the app.</span></p><p><span>If you choose to use our Service, then you agree to the collection and use of information in relation to this policy.</span></p><h2 id="Information-Collection-and-Use" data-id="Information-Collection-and-Use"><span>Information Collection and Use</span></h2><p><span>We automatically collect certain information when you visit, use, or navigate the Services. This information does not reveal your specific identity (like your name or contact information) but may include device and usage information, such as your IP address, browser and device characteristics, operating system, language preferences, referring URLs, device name, country, location, information about how and when you use our Services, and other technical information. This data will be associated with a unique identifier corresponding to your device. We do not collect or store any other personally identifiable details.</span></p><h4 id="Log-and-Usage-Data" data-id="Log-and-Usage-Data"><span>Log and Usage Data</span></h4><p><span>Log and usage data is service-related, diagnostic, usage, and performance information our app automatically collects when you access or use our Services and which we record in log files. In the case of an error in the app we collect data and information (through third-party providers). This Log Data may include information such as your device Internet Protocol (“IP”) address, device name, operating system version, the configuration of the app when utilizing our Service, the time and date of your use of the Service, and other statistics.</span></p><h2 id="Third-Party-Service-Providers" data-id="Third-Party-Service-Providers"><span>Third-Party Service Providers</span></h2><p><span>We may share your data with third-party vendors, service providers, contractors, or agents (“third parties”) who perform services for us or on our behalf and require access to such information to do that work. The third parties we may share personal information with are as follows:</span></p><ul>
<li><a href="https://www.google.com/policies/privacy/" target="_blank" rel="noopener"><span>Google Play Services</span></a></li>
<li><a href="https://gameanalytics.com/privacy" target="_blank" rel="noopener"><span>GameAnalytics</span></a></li>
<li><a href="https://godotengine.org/privacy-policy" target="_blank" rel="noopener"><span>Godot</span></a></li>
</ul><p><span>The privacy policies of each of these third parties are linked above.</span></p><h2 id="Changes-to-This-Privacy-Policy" data-id="Changes-to-This-Privacy-Policy"><span>Changes to This Privacy Policy</span></h2><p><span>We may update our Privacy Policy from time to time. The updated version will be indicated by an updated “Revised” date and the updated version will be effective as soon as it is accessible. Thus, you are advised to review this page periodically for any changes. We will notify you of any changes by posting the new Privacy Policy on this page.</span></p><h2 id="Contact-Us" data-id="Contact-Us"><span>Contact Us</span></h2><p><span>If you have any questions or suggestions about our Privacy Policy, do not hesitate to contact us via email at:</span></p><p><span>android-support@csma.technology,<br>ios-support@csma.technology,</span></p><p><span>or by post at:</span></p><p><span>CSMA Technology, LLC</span><br>
<span>123 SW 17th Rd</span><br>
<span>Unit 106</span><br>
<span>Miami, FL 33129</span><br>
<span>United States</span></p></div>
`;
